name: release
on:
  push:
    branches:
      - main
    paths:
      - charts/**
  workflow_dispatch: {}
permissions:
  contents: write
  pages: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: azure/setup-helm@v5

      - name: Add the common repository
        run: helm repo add common https://rubxkube.github.io/common-charts

      - uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
